baseURL: "/"
DefaultContentLanguage: en

params:
    name: 'Boilerplate'
    showLanguageSelector: true #true if bilingual site - false if unilingua
    usebasin: '' #endpoint for forms
    googlemap: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2797.6201892652552!2d-74.30512348421598!3d45.4774544405795!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccec91b3da1b1ef%3A0x9da8296b7baffcb3!2s119%20Rue%20Saint-Pierre%2C%20Rigaud%2C%20QC%20J0P%201P0!5e0!3m2!1sen!2sca!4v1605810811417!5m2!1sen!2sca' # Map code of Google
    gtm: ''
    hours:
        hour1en: 'Mon to Fri - 8:00-17:00' #Footer Hours Line #1
        hour2en: 'Sat - On Call' #Footer Hours Line #2
        hour3en: 'Sun - On Call' #Footer Hours Line #3
        hour1fr: 'Lun - Ven - 8:00-17:00' #Footer Hours Line #1 in French / Leave empty if it does not apply
        hour2fr: 'Sam - Sur Appel' #Footer Hours Line #1 in French / Leave empty if it does not apply
        hour3fr: 'Dim - Sur Appel' #Footer Hours Line #1 in French / Leave empty if it does not apply
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: ''
    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Tu-Fr 13:00-16:00'
        logo: "https://placeholder.com/wp-content/uploads/2018/10/placeholder.com-logo2.png"
        image: "img/og.jpg"
        address: 8 rue principale sud,
        address2: '#103'
        city: Delson
        region: QC
        country: Canada
        postalcode: J5B 0A2
        phone: +1-888-888-8888
        email: sebassaf@gmail.com

languages:
  fr:
    languageCode: fr
    title: SebAssaf.com
    description: Site Tagline
    contentDir: content/fr
    menu:
      main:
        - name: Accueil
          url: '#'
          weight: 1
        - name: À Propos
          url: 'a-propos/'
          weight: 2
        - name: Services
          url: "services/"
          weight: 3
        - name: Contact
          url: "contact/"
          weight: 4

  en:
    languageCode: en
    title: SebAssaf.com
    description: Site Tagline
    contentDir: content/en
    menu:
      main:
        - name: Home
          url: '/'
          weight: 1
        - name: About
          url: 'about/'
          weight: 2
        - name: Services
          url: 'services/'
          weight: 3
        - name: Contact
          url: 'contact/'
          weight: 4


enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart